import {fontConfig} from './FontConfig';

export const COLORS = {
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  TEXT_PRIMARY_NORMAL: '#000000',
  TEXT_PRIMARY_DARK: '#CCCCCC',
  TEXT_INACTIVE_NORMAL: '#B1B1B1',
  TEXT_INACTIVE_DARK: '#414141',
  TRACK_SUB_MENU_BLACK: '#262626',
  BLACK_VARIANT_1: '#1C1C1C',
  SILVER_ICON_COLOR: '#565656',
  SILVER_VARAINT_1: '#DFDFDF',
  SILVER_VARAINT_2: '#F2F2F2',
  SILVER_VARAINT_3: '#D8D8D8',
  SILVER_VARAINT_3_BLK: '#4B4B4B',
  BACKGROUND_PRIMARY_NORMAL: '#FFFFFF',
  BACKGROUND_VARAINT_1: '#F4F4F4',
  BACKGROUND_SECONDARY_NORMAL: '#F8F8F8',
  BACKGROUND_SECONDARY_DARK: '#393939',
  BACKGROUND_PRIMARY_DARK: '#161616',
  BACKGROUND_VARIANT_2: '#fbfbfb',
  BACKGROUND_VARAINT_3: '#EBEBEB',
  BACKGROUND_VARAINT_3_BLK: '#202020',
  BACKGROUND_VARAINT_5: '#E6E6E6',
  BACKGROUND_VARAINT_5_BLK: '#262525',
  BACKGROUND_VARAINT_6: '#E2E2E2',
  TEXT_VARAINT_1: '#8a8a8a',
  TEXT_VARAINT_1_BLK: '#e6e6e6',
  TEXT_VARIANT_2: '#505050',
  BLACK_VARIANT_2: '#1e1e1e',
  BLACK_VARAINT_3: '#1d1d1d',
  GREEN: '#69F499',
  GREEN_ICON_BACKGROUND: '#24EE6E',
  GREEN_VARAINT_1: '#71ffb2',
  GREEN_VARIANT_2: '#00ff88',
  ICON_COLOR_VARAINT: '#5b5b5b',
  ICON_COLOR_VARAINT1: '#bbbbbb',
  ICON_COLOR_VARAINT1_BLK: '#3a3a3a',
  ICON_COLOR_VARAINT_2: '#292929',
  UNDERLINE_COLOR: '#707070',
  THUMBNAIL_BORDER_COLOR: '#C8C8C8',
  TEXT_COMMON_SILVER: '#717171',
  YELLOW_BACKGROUND: '#F7FF00',
  LABEL_COLOR: '#BEBEBE',
  RED: '#FF7777',
  TRANSPARENT: 'transparent',
  PROFILE_TEXT: '#151515',
  BORDER_COLOR: '#D6D6D6',
};
export const fontSizes = {
  titleh1: 40,
  titleh2: 34,
  h1: 30,
  h2: 24,
  h3: 20,
  h4: 18,
  paragraph: 14,
  small: 12,
  extraSmall: 10,
  xxs: 8,
};
export const SPACING = {
  ZERO: 0,
  TINY: 3,
  COMPACT: 5,
  XXS: 8,
  EXTRA_SMALL: 10,
  SMALL: 15,
  SMALL_1: 13,
  MEDIUM: 17,
  NORMAL: 20,
  LARGE: 23,
  EXTRA_LARGE: 25,
  LARGE4: 30,
  LARGE3: 33,
  LARGE2: 35,
  LARGE1: 50,
};

export const normalTheme = {
  colors: {
    backgroundPrimary: COLORS.BACKGROUND_PRIMARY_NORMAL,
    backgroundSecondary: COLORS.BACKGROUND_SECONDARY_NORMAL,
    backgroundVariant1: COLORS.BACKGROUND_VARAINT_1,
    backgroundVariant2: COLORS.SILVER_VARAINT_2,
    backgroundVariant3: COLORS.BACKGROUND_VARAINT_3,
    backgroundVariant4: COLORS.WHITE,
    backgroundVariant5: COLORS.BACKGROUND_VARAINT_5,
    backgroundVariant6: COLORS.BACKGROUND_VARAINT_6,
    backgroundVariant7: COLORS.WHITE,
    backgroundVariant8: COLORS.TEXT_VARAINT_1_BLK,
    backgroundVariant9: COLORS.BACKGROUND_VARIANT_2,
    backgroundSilverVariant: COLORS.SILVER_VARAINT_3,
    textPrimary: COLORS.TEXT_PRIMARY_NORMAL,
    textSecondary: COLORS.BLACK,
    textSilverVariant: COLORS.BLACK,
    textInactive: COLORS.TEXT_INACTIVE_NORMAL,
    textSilverCommon: COLORS.TEXT_COMMON_SILVER,
    textVariant1: COLORS.TEXT_VARAINT_1,
    textVariant2: COLORS.TEXT_VARIANT_2,
    buttonPrimary: COLORS.BLACK,
    buttonTextPrimary: COLORS.WHITE,
    iconHeader: COLORS.SILVER_ICON_COLOR,
    borderColor: COLORS.BORDER_COLOR,
    labelColor: COLORS.LABEL_COLOR,
    error: COLORS.RED,
    underlineColor: COLORS.UNDERLINE_COLOR,
    thumbnailBorder: COLORS.THUMBNAIL_BORDER_COLOR,
    green: COLORS.GREEN,
    backgroundGreen: COLORS.GREEN_ICON_BACKGROUND,
    backgroundGreenVariant1: COLORS.BLACK_VARIANT_2,
    iconColorVariant: COLORS.ICON_COLOR_VARAINT,
    iconColorVariant1: COLORS.ICON_COLOR_VARAINT1,
    iconColorVariant2: COLORS.TEXT_VARAINT_1_BLK,
  },
  fonts: fontConfig.ProximaNova,
};

export const darkTheme = {
  colors: {
    backgroundPrimary: COLORS.BACKGROUND_PRIMARY_DARK,
    backgroundSecondary: COLORS.BACKGROUND_SECONDARY_DARK,
    backgroundVariant1: COLORS.BACKGROUND_PRIMARY_DARK,
    backgroundVariant2: COLORS.BLACK_VARIANT_1,
    backgroundVariant3: COLORS.BACKGROUND_VARAINT_3_BLK,
    backgroundVariant4: COLORS.BLACK_VARIANT_1,
    backgroundVariant5: COLORS.BACKGROUND_VARAINT_5_BLK,
    backgroundVariant6: COLORS.WHITE,
    backgroundVariant7: COLORS.TRACK_SUB_MENU_BLACK,
    backgroundVariant8: COLORS.BLACK_VARAINT_3,
    backgroundVariant9: COLORS.BACKGROUND_PRIMARY_DARK,
    backgroundSilverVariant: COLORS.SILVER_VARAINT_3_BLK,
    textPrimary: COLORS.WHITE,
    textSilverVariant: COLORS.SILVER_VARAINT_1,
    textSilverCommon: COLORS.TEXT_COMMON_SILVER,
    textSecondary: COLORS.SILVER_ICON_COLOR,
    textInactive: COLORS.TEXT_INACTIVE_DARK,
    textVariant1: COLORS.TEXT_VARAINT_1_BLK,
    textVariant2: COLORS.WHITE,
    buttonPrimary: COLORS.WHITE,
    buttonTextPrimary: COLORS.BLACK,
    iconHeader: COLORS.SILVER_ICON_COLOR,
    borderColor: COLORS.TRANSPARENT,
    labelColor: COLORS.LABEL_COLOR,
    error: COLORS.RED,
    underlineColor: COLORS.UNDERLINE_COLOR,
    thumbnailBorder: COLORS.GREEN,
    green: COLORS.GREEN,
    backgroundGreen: COLORS.WHITE,
    backgroundGreenVariant1: COLORS.GREEN_VARAINT_1,
    iconColorVariant: COLORS.WHITE,
    iconColorVariant1: COLORS.ICON_COLOR_VARAINT1_BLK,
    iconColorVariant2: COLORS.ICON_COLOR_VARAINT_2,
  },
  fonts: fontConfig.ProximaNova,
};
